### ISSUE TITLE
Feature request: Add friendly names for bookmarks

### ISSUE THREAD

**Issue by francisbarton** [damolinx/vscode-bookmarks#1]
Hi,

I wanted to say thanks for developing this extension. It was just what I wanted.
A "nice to have" feature would be to be able to rename a bookmark with a "friendly" name e.g. "My bash profile", instead of the file name itself being shown. Ideally you would right-click on the bookmark and "rename" would come up as an option.
The file name should still be shown in the bookmarks list by default though 😃.

**Comment by damolinx** [comment]
Implementing this feature requires to upgrade the data storage format first to allow arbitrary metadata. Initial work is here: https://github.com/damolinx/vscode-bookmarks/commit/b9457bdca4c7318ccac1d8bd8c33af48f542b092

A few updates to the internal OM will be needed (currently WIP) and then the UI experience.

**Comment by francisbarton** [comment]
Thanks, that's great

**Comment by damolinx** [comment]
v0.3.0 should allow you to "rename" a node which allows you to set a custom name.  Most of the work went into moving internals around so the experience is basic (planning to update it over time).

**Comment by francisbarton** [comment]
Wonderful, thank you
