### ISSUE TITLE
Create multiple Filtered Views and name them

### ISSUE THREAD

**Issue by sfeldkamp** [damolinx/vscode-bookmarks#2]
It would be nice to be able to create multiple Filtered Views and to give each a name.  

I use the extension mostly to focus on my current work in progress.  Sometimes that's more than one thing.  I can also see others using it to create views of different features of the project that they may come back to over the course of the project.

**Comment by damolinx** [comment]
Playing with a few ideas on how to manage the views, e.g.
 - add tags to bookmarks.
 - d'n'd bookmarks under custom folders.

**Comment by damolinx** [comment]
v0.4.0 contains folder support (should be released later today after publish flow completes).
