### ISSUE TITLE
Design a search bar

### ISSUE THREAD

**Issue by oranger-lc** [damolinx/vscode-bookmarks#5]
I have over a hundred global bookmarks now, and it's a bit difficult to find what I want. Can you design a search bar? 

I'm not sure how much work it will take. 

If it's too complicated, then just ignore me.

This extension is very very very satisfying to me, thank you！

**Comment by damolinx** [comment]
VS Code does not support custom UI on tree views (i.e. I cannot add a search bar on the `Bookmarks` view itself - not at least without going the WebView way which would be a major undertaking), so I [added](https://github.com/damolinx/vscode-bookmarks/commit/9849e0e6a13a9fb73546da035a931d07dedd1133) a new `Bookmarks: Search` command that uses a quickpick control (and accessible from the context menu on the `Bookmarks` title bar context menu).

<p align=center>
<img width="300" alt="image" src="https://github.com/user-attachments/assets/21a7d24e-6da1-4a47-b686-dfd94dcd4015">
</p>

This will come out in 0.4.8 published later today,
